name: Docker build
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ghcr.io/${{ github.repository_owner }}/simple-flask
          password: ${{ secrets.GITHUB_TOKEN }}
          path: Docker
          cache: true
          cache_registry: simple-docker/cache